'https://catalogue.dataspace.copernicus.eu':
  username: !ENV 'COPERNICUS_DATA_SPACE_USERNAME'
  password: !ENV 'COPERNICUS_DATA_SPACE_PASSWORD'
  authentication_type: 'oauth2'
  token_url: 'https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token'
  client_id: 'cdse-public'
  max_parallel_downloads: 4