"""
Django settings for geospaas_project project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'chu2p96if%&^09w6okqjwc-%+hmpc1t3@b&i8*+3nvdk!xpdb0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'leaflet',
    'django_forms_bootstrap',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'geospaas.base_viewer',
    'geospaas.catalog',
    'geospaas.vocabularies',
    'geospaas_processing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geospaas_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geospaas_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'HOST': os.getenv('GEOSPAAS_DB_HOST', 'localhost'),
        'PORT': os.getenv('GEOSPAAS_DB_PORT', '5432'),
        'NAME': os.getenv('GEOSPAAS_DB_NAME', 'geodjango'),
        'USER': os.getenv('GEOSPAAS_DB_USER', 'geodjango'),
        'PASSWORD': os.getenv('GEOSPAAS_DB_PASSWORD'),
        'CONN_MAX_AGE': int(os.getenv('GEOSPAAS_CONN_MAX_AGE', '600')),
    }
}
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/site_media/media/'
STATIC_ROOT = "/site_media/static"
MEDIA_ROOT = "/site_media/media/"
DOWNLOADS_ROOT = "/site_media/downloads"
PRODUCTS_ROOT = "/site_media/products"
STATICFILES_DIRS = ["/project/static"]
SERIALIZATION_MODULES = {"geojson": "django.contrib.gis.serializers.geojson"}
ALLOWED_HOSTS = ['*']
SPATIALITE_LIBRARY_PATH = 'mod_spatialite'


SHOW_LOCAL_ADDRESS = True

LEAFLET_CONFIG = {
    'NO_GLOBALS': False,
}
